[package]
name = "bevy-test"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.18.1"
rand = "0.10.1"
rand_chacha = "0.10.0"

# [profile.release]
# opt-level = "z"      # optimize for size ("s" is another good choice)
# lto = "fat"          # or "thin" if compile time matters
# codegen-units = 1
# panic = "abort"
# strip = true
